### ISSUE TITLE
feat： support sql render

### ISSUE THREAD

**Issue by codering** [holmofy/spring-data-jdbc-criteria#4]
spring-data-jdbc 有一个是sql工具类，方便自己动态生成复杂sql， 但使用时必须要自己创建Table和Column对象，不方便，希望能通过apt自动生成。 

see https://github.com/spring-projects/spring-data-relational/blob/main/spring-data-relational/src/test/java/org/springframework/data/relational/core/sql/render/SelectRendererUnitTests.java

**Comment by holmofy** [comment]
已经ok了
